#pragma once

#define UART_ENABLED 1
#define UART0_ENABLED 1

#define NRF_LOG_ENABLED 0
#define NRF_LOG_BACKEND_SERIAL_USES_UART 1
#define NRF_LOG_DEFERRED 0

#define NRF_LOG_BACKEND_SERIAL_UART_TX_PIN 27
#define NRF_LOG_BACKEND_SERIAL_UART_RX_PIN 28
#define NRF_LOG_BACKEND_UART_INSTANCE 0
